name: normalize composer.json

on:
  push:
    paths:
      - "composer.json"

jobs:
  normalize:
    runs-on: [ self-hosted ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: normalize composer.json
        run: |
          composer config --no-plugins allow-plugins.ergebnis/composer-normalize true
          composer global require ergebnis/composer-normalize
          composer normalize
      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: normalize composer.json
