name: normalize composer.json
true:
  push:
    paths:
    - composer.json
jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: normalize composer.json
      run: 'composer config --no-plugins allow-plugins.ergebnis/composer-normalize
        true

        composer global require ergebnis/composer-normalize

        composer normalize

        '
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: normalize composer.json
